load_paths:
  - test/src
  - assets
  - polyfills
  - src

logical_paths:
  - trix.js
  - test.js
  - trix.css

build:
  logical_paths:
    - trix.js
    - trix-core.js
    - trix.css
  path: dist
  js_compressor: uglifier

plugins:
  sauce_labs:
    browsers:
      Safari:
        platform: Mac
        version: -3
      Google Chrome:
        os: Mac, Windows, Linux
        version: -2
      Firefox:
        os: Mac, Windows, Linux
        version: -2
      Internet Explorer:
        version: -1
      Motorola Droid 4 Emulator:
        version: [5.1, 5.0, 4.4]
      iPhone:
        version: [9.1, 9.0, 8.4, 7.1]
    test_config:
      selenium_version: 2.47.1
      video_upload_on_pass: false
      record_screenshots: false
      record_logs: false
